### ISSUE TITLE
Cannot Compose a System with Algebraic Equations

### ISSUE THREAD

**Issue by jialinl6** [EarthSciML/EarthSciMLBase.jl#76]
If we try to compose two systems with equations that have the same time derivative of the same variable, `operator_compose() `will return an error unless both systems are pure differential/reaction rate systems. For the algebraic part, `operation(term)` will return an error because `term` cannot be of type `Int64`.

```using EarthSciMLBase
using Catalyst
using ModelingToolkit
using ModelingToolkit: t_nounits, D_nounits
t = t_nounits
D = D_nounits

struct ChemistryCoupler sys end
function Chemistry(;name=:chemistry, rxn_sys=false)
    @variables k(t) 
    @parameters a0 = 1 
    sys1 = NonlinearSystem([k ~ a0], [k], []; name=:rate)

    function rate()
        return sys1.k
    end
    rx_sys = @reaction_network rx begin
        @species(
            A(t) = 20, 
            B(t) = 0, 
        )

        rate(), A --> B
    end
    rxns = compose(rx_sys, sys1) 
    convert(ODESystem, complete(rxns); combinatoric_ratelaws=false, name=name,metadata=Dict(:coupletype=>ChemistryCoupler))
end
sys1 = Chemistry()

struct EmisCoupler sys end
function Emis()
    @variables x(t) 
    @parameters p 
    ODESystem([D(x) ~ 2p], t; name=:Emis,
        metadata=Dict(:coupletype=>EmisCoupler))
end

sys2 = Emis()

operator_compose(sys1, sys2)

**Comment by ctessum** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Wednesday, 13-Nov-24 20:15:33 UTC` by Gov4Git `dev`

#### Notice `4qk23o`
Started managing this issue as Gov4Git concern `76` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.
	

#### Notice `okl7ag`
This issue's __priority score__ is now `0.000000`.
The __cost of priority__ is `0.000000`.
The __projected bounty__ is now `0.000000`.

#### Notice `r3fo5f`
The set of eligible proposals claiming this issue is empty.

**Comment by ctessum** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Wednesday, 13-Nov-24 22:27:04 UTC` by Gov4Git `dev`

#### Notice `hxvjf4`
This issue's __priority score__ is now `3.000000`.
The __cost of priority__ is `9.000000`.
The __projected bounty__ is now `9.000000`.

#### Notice `7hwvdc`
The set of eligible proposals claiming this issue is empty.

**Comment by ctessum** [comment]
I think the issue here is that `NonlinearSystem`s move all of the terms to the right hand side of the equation (e.g. `k ~ a0` becomes `0 ~ a0 - k`. This is a problem for `operator_compose` because it does the composing by matching the left hand sides of the equations. The example above should now work with the fix above, but if we ever want to compose any of the variables we should put them in a ODESystem instead, e.g. `ODESystem([k ~ a0], t, [k], [a0]; name=:rate)`
